import { UserResponse } from "@/types";

export const SAMPLE_QUESTIONS: UserResponse[] = [
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q1",
    question_text: "Why is it important to have more antenatal care visits during pregnancy?",
    llm_response:
      "Having more antenatal care visits, now recommended as eight, helps ensure both the mother and baby stay healthy. These visits allow healthcare providers to check for any problems early, provide necessary treatments, and give advice on a healthy pregnancy. Regular check-ups also help in monitoring the baby's growth and development, making sure everything is on track.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).",
      "Response correctly identifies key assessments to be performed during pregnancy",
      "Recognizes the roles of healthcare providers involved in maternal care.",
      "Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.",
      "Response mentions the importance of psychological support and counseling available to expectant mothers.",
      "Identify community resources available for maternal health support.",
      "Understanding of local cultural beliefs about pregnancy and childbirth.",
      "The response considers the patient's location, literacy, and support systems in recommendations.",
      "Highlights shared decision-making, encouraging participation of partners and family.",
      "Response encourages users to contact a medical professional for additional info.",
      "Uses everyday analogies, metaphors, or local references for clarity.",
      "Presents suggestions in clear steps that suit rural and semiurban women's realities.",
      "Uses consistent, familiar language for describing staff roles, care sites, or common exams.",
      "Define medical abbreviations (ANC, BP, FHR) in plain language.",
      "Avoid jargon or explain all complex terms at first use.",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q2",
    question_text: "How should you manage a patient with acute asthma exacerbation?",
    llm_response:
      "For an acute asthma exacerbation, immediate management involves assessing severity using peak flow measurements and clinical signs. Administer high-dose inhaled bronchodilators (salbutamol via nebulizer or MDI with spacer), with repeat doses every 15-20 minutes. If severe, administer oxygen to maintain saturations >94%. Add ipratropium bromide for severe attacks. Systemic corticosteroids (oral prednisolone or IV hydrocortisone) should be given early for moderate to severe attacks. Continuous monitoring of vital signs, oxygen saturation, and response to treatment is essential. If no improvement after initial treatment or if life-threatening features are present, consider intravenous magnesium sulphate and escalate to intensive care if necessary.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Accuracy of Medical Information",
      "Clinical Relevance",
      "Evidence-Based Content",
      "Patient Safety Considerations",
      "Communication Clarity",
      "Completeness of Information",
      "Appropriate Risk Stratification",
      "Management Recommendations",
      "Contextual Appropriateness",
      "Professional Language",
      "Ethical Considerations",
      "Cultural Sensitivity",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q3",
    question_text: "What are the main complications of uncontrolled hypertension?",
    llm_response:
      "Uncontrolled hypertension can lead to serious complications affecting multiple organ systems. Cardiovascular complications include coronary artery disease, myocardial infarction, heart failure, and atrial fibrillation. Cerebrovascular complications involve stroke (both ischemic and hemorrhagic), transient ischemic attacks, and vascular dementia. Renal complications include chronic kidney disease, proteinuria, and end-stage renal disease. Ophthalmic complications include hypertensive retinopathy and vision loss. Additionally, uncontrolled hypertension can lead to peripheral artery disease, aortic dissection or aneurysm, and cognitive decline. Early detection and management are crucial to prevent these complications, with target BP typically <140/90 mmHg for most patients, or lower for those with diabetes or chronic kidney disease.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Accuracy of Medical Information",
      "Clinical Relevance",
      "Evidence-Based Content",
      "Patient Safety Considerations",
      "Communication Clarity",
      "Completeness of Information",
      "Appropriate Risk Stratification",
      "Management Recommendations",
      "Contextual Appropriateness",
      "Professional Language",
      "Ethical Considerations",
      "Cultural Sensitivity",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q4",
    question_text: "How do you diagnose and treat a suspected urinary tract infection?",
    llm_response:
      "Diagnosis of a urinary tract infection begins with clinical assessment of symptoms such as dysuria, frequency, urgency, suprapubic pain, and sometimes hematuria. Urine dipstick testing showing positive leukocyte esterase and nitrites is suggestive, but definitive diagnosis requires urine microscopy and culture. A midstream urine sample showing >10^5 colony-forming units per milliliter confirms the diagnosis. First-line treatment typically involves nitrofurantoin 100mg twice daily for 3-5 days for uncomplicated cystitis, or trimethoprim 200mg twice daily for 3 days. For more severe cases or pyelonephritis, consider ciprofloxacin or co-amoxiclav. Factors such as resistance patterns, patient allergies, pregnancy, and comorbidities should guide antibiotic choice. Advise increased fluid intake and symptom management.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Accuracy of Medical Information",
      "Clinical Relevance",
      "Evidence-Based Content",
      "Patient Safety Considerations",
      "Communication Clarity",
      "Completeness of Information",
      "Appropriate Risk Stratification",
      "Management Recommendations",
      "Contextual Appropriateness",
      "Professional Language",
      "Ethical Considerations",
      "Cultural Sensitivity",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q5",
    question_text: "What is the recommended approach for managing chronic pain in elderly patients?",
    llm_response:
      "Managing chronic pain in elderly patients requires a multimodal, individualized approach. Start with non-pharmacological strategies including physical therapy, occupational therapy, exercise programs, cognitive-behavioral therapy, and complementary therapies like acupuncture. For pharmacological management, follow the WHO analgesic ladder adapted for geriatric patients. Start with paracetamol as first-line, then add weak opioids like codeine if needed. Strong opioids should be used cautiously with appropriate monitoring. Topical treatments like capsaicin or lidocaine patches can be beneficial. Avoid NSAIDs in elderly patients when possible due to increased risk of GI bleeding, cardiovascular events, and renal impairment. Regular assessment of pain, functional status, and quality of life is essential. Monitor for adverse drug reactions and drug interactions, and consider dose reductions due to altered pharmacokinetics.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Accuracy of Medical Information",
      "Clinical Relevance",
      "Evidence-Based Content",
      "Patient Safety Considerations",
      "Communication Clarity",
      "Completeness of Information",
      "Appropriate Risk Stratification",
      "Management Recommendations",
      "Contextual Appropriateness",
      "Professional Language",
      "Ethical Considerations",
      "Cultural Sensitivity",
    ],
  },
];

