import { UserResponse } from "@/types";

export const SAMPLE_QUESTIONS: UserResponse[] = [
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q1",
    question_text: "Why is it important to have more antenatal care visits during pregnancy?",
    llm_response:
      "Having more antenatal care visits, now recommended as eight, helps ensure both the mother and baby stay healthy. These visits allow healthcare providers to check for any problems early, provide necessary treatments, and give advice on a healthy pregnancy. Regular check-ups also help in monitoring the baby's growth and development, making sure everything is on track.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).",
      "Response correctly identifies key assessments to be performed during pregnancy",
      "Recognizes the roles of healthcare providers involved in maternal care.",
      "Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.",
      "Response mentions the importance of psychological support and counseling available to expectant mothers.",
      "Identify community resources available for maternal health support.",
      "Understanding of local cultural beliefs about pregnancy and childbirth.",
      "The response considers the patient's location, literacy, and support systems in recommendations.",
      "Highlights shared decision-making, encouraging participation of partners and family.",
      "Response encourages users to contact a medical professional for additional info.",
      "Uses everyday analogies, metaphors, or local references for clarity.",
      "Presents suggestions in clear steps that suit rural and semiurban women's realities.",
      "Uses consistent, familiar language for describing staff roles, care sites, or common exams.",
      "Define medical abbreviations (ANC, BP, FHR) in plain language.",
      "Avoid jargon or explain all complex terms at first use.",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q2",
    question_text: "I am pregnant and often feel a burning sensation in my chest. What can I do to relieve this discomfort?",
    llm_response:
      "Heartburn during pregnancy is common. You can try simple remedies like eating smaller, frequent meals, avoiding spicy and fried foods, and waiting at least 2-3 hours after eating before lying down. Drinking a glass of cold milk or mixing a spoonful of honey in warm water can also help soothe the burning sensation. If symptoms persist, consult a local healthcare provider or an Ayush doctor. ",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).",
      "Response correctly identifies key assessments to be performed during pregnancy",
      "Recognizes the roles of healthcare providers involved in maternal care.",
      "Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.",
      "Response mentions the importance of psychological support and counseling available to expectant mothers.",
      "Identify community resources available for maternal health support.",
      "Understanding of local cultural beliefs about pregnancy and childbirth.",
      "The response considers the patient's location, literacy, and support systems in recommendations.",
      "Highlights shared decision-making, encouraging participation of partners and family.",
      "Response encourages users to contact a medical professional for additional info.",
      "Uses everyday analogies, metaphors, or local references for clarity.",
      "Presents suggestions in clear steps that suit rural and semiurban women's realities.",
      "Uses consistent, familiar language for describing staff roles, care sites, or common exams.",
      "Define medical abbreviations (ANC, BP, FHR) in plain language.",
      "Avoid jargon or explain all complex terms at first use.",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q3",
    question_text: "I was very active before pregnancy. Can I continue my usual exercises while pregnant or after delivery?",
    llm_response:
      "Yes, you can continue your habitual exercises, even vigorous ones, during pregnancy and postpartum, provided you feel comfortable. However, always listen to your body and consult with a healthcare provider when possible. Start slowly and adjust the intensity as needed. It's also important to limit sitting for long periods.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).",
      "Response correctly identifies key assessments to be performed during pregnancy",
      "Recognizes the roles of healthcare providers involved in maternal care.",
      "Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.",
      "Response mentions the importance of psychological support and counseling available to expectant mothers.",
      "Identify community resources available for maternal health support.",
      "Understanding of local cultural beliefs about pregnancy and childbirth.",
      "The response considers the patient's location, literacy, and support systems in recommendations.",
      "Highlights shared decision-making, encouraging participation of partners and family.",
      "Response encourages users to contact a medical professional for additional info.",
      "Uses everyday analogies, metaphors, or local references for clarity.",
      "Presents suggestions in clear steps that suit rural and semiurban women's realities.",
      "Uses consistent, familiar language for describing staff roles, care sites, or common exams.",
      "Define medical abbreviations (ANC, BP, FHR) in plain language.",
      "Avoid jargon or explain all complex terms at first use.",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q4",
    question_text: "When should I start taking care of my pregnancy?",
    llm_response:
      "As soon as you think you might be pregnant, it's important to see a healthcare provider. They can guide you through the necessary steps, which include HIV counseling and testing. Early care ensures a healthier pregnancy for you and your baby. Visit your nearest Integrated Counselling and Testing Centre (ICTC) or a trusted healthcare facility.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).",
      "Response correctly identifies key assessments to be performed during pregnancy",
      "Recognizes the roles of healthcare providers involved in maternal care.",
      "Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.",
      "Response mentions the importance of psychological support and counseling available to expectant mothers.",
      "Identify community resources available for maternal health support.",
      "Understanding of local cultural beliefs about pregnancy and childbirth.",
      "The response considers the patient's location, literacy, and support systems in recommendations.",
      "Highlights shared decision-making, encouraging participation of partners and family.",
      "Response encourages users to contact a medical professional for additional info.",
      "Uses everyday analogies, metaphors, or local references for clarity.",
      "Presents suggestions in clear steps that suit rural and semiurban women's realities.",
      "Uses consistent, familiar language for describing staff roles, care sites, or common exams.",
      "Define medical abbreviations (ANC, BP, FHR) in plain language.",
      "Avoid jargon or explain all complex terms at first use.",
    ],
  },
  {
    user_id: "admin-demo-user",
    user_name: "Admin Demo User",
    user_profession: "General Practitioner",
    email: "admin@demo.com",
    question_id: "demo-q5",
    question_text: "I've recently given birth and am unsure about the best way to care for myself and my baby. What should I keep in mind regarding my health and breastfeeding?",
    llm_response:
      "Postnatal care is essential for your recovery and your baby's health. Ensure you have regular check-ups with a healthcare provider. Breastfeeding is highly recommended as it provides essential nutrients for your baby. Drink plenty of fluids, eat a balanced diet, and rest when possible. If you experience any pain, fever, or unusual symptoms, consult your healthcare provider promptly.",
    status: "assigned",
    assigned_at: new Date().toISOString(),
    user_answer: "",
    rubrics: [
      "Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).",
      "Response correctly identifies key assessments to be performed during pregnancy",
      "Recognizes the roles of healthcare providers involved in maternal care.",
      "Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.",
      "Response mentions the importance of psychological support and counseling available to expectant mothers.",
      "Identify community resources available for maternal health support.",
      "Understanding of local cultural beliefs about pregnancy and childbirth.",
      "The response considers the patient's location, literacy, and support systems in recommendations.",
      "Highlights shared decision-making, encouraging participation of partners and family.",
      "Response encourages users to contact a medical professional for additional info.",
      "Uses everyday analogies, metaphors, or local references for clarity.",
      "Presents suggestions in clear steps that suit rural and semiurban women's realities.",
      "Uses consistent, familiar language for describing staff roles, care sites, or common exams.",
      "Define medical abbreviations (ANC, BP, FHR) in plain language.",
      "Avoid jargon or explain all complex terms at first use.",
    ],
  },
];

